package com.github.tatercertified.oxidizium;
import com.github.tatercertified.oxidizium.utils.annotation.*;
public interface NativeInterface {
float sin_double(double x);
float sin_float(float x);
float cos_float(float x);
float cos_double(double x);
float lithium_sin_float(float x);
float lithium_cos_float(float x);
float lithium_sin_double(double x);
float lithium_cos_double(double x);
float sqrt_float(@PositiveOnly float x);
int floor_float(float x);
int floor_double(double x);
long floor_long(double x);
float abs_float(float x);
int abs_int(int x);
int ceil_float(float x);
int ceil_double(double x);
long ceil_long(double x);
int clamp_int(int x, @Min int min, @Max int max);
long clamp_long(long x, @Min long min, @Max long max);
float clamp_float(float x, @Min float min, @Max float max);
double clamp_double(double x, @Min double min, @Max double max);
double clamp_lerp_double(double start, double end, double delta);
float clamp_lerp_float(float start, float end, float delta);
int abs_max_int(int i, int j);
float abs_max_float(float i, float j);
double abs_max(double a, double b);
int abs_max_difference(int i, int j, int k, int l);
int floor_div(int dividend, @NonZero int divisor);
boolean approximately_equals_float(float a, float b);
boolean approximately_equals_double(double a, double b);
int floor_mod_int(int dividend, @NonZero int divisor);
float floor_mod_float(float dividend, @NonZero float divisor);
double floor_mod_double(double dividend, @NonZero double divisor);
boolean is_multiple_of(int a, @NonZero int b);
byte pack_degrees(float degrees);
float unpack_degrees(byte packed_degrees);
int wrap_degrees_int(int degrees);
float wrap_degrees_long(long degrees);
float wrap_degrees_float(float degrees);
double wrap_degrees_double(double degrees);
float subtract_angles(float start, float end);
float angle_between(float first, float second);
float clamp_angle(float value, float mean, float delta);
float step_towards(float from, float to, float step);
float step_unwrapped_angle_towards(float from, float to, float step);
int smallest_encompassing_power_of_two(int value);
int smallest_encompassing_square_side_length(@PositiveOnly int value);
boolean is_power_of_two(int value);
int ceil_log_2(int value);
int floor_log_2(int value);
int pack_rgb(float red, float green, float blue);
float fractional_part_float(float value);
double fractional_part_double(double value);
long hash_code(int x, int y, int z);
double get_lerp_progress_double(double value, double start, double end);
float get_lerp_progress_float(float value, float start, float end);
double atan_2(double y, double x);
float inverse_sqrt_float(@PositiveOnly float x);
double inverse_sqrt_double(@PositiveOnly double x);
double fast_inverse_sqrt(double x);
float fast_inverse_sqrt_float(float x);
float fast_inverse_cbrt(float x);
int hsv_to_rgb(@PositiveOnly float hue, @PositiveOnly float saturation, @PositiveOnly float value);
int hsv_to_argb(@PositiveOnly float hue, @PositiveOnly float saturation, @PositiveOnly float value, @PositiveOnly int alpha);
int ideal_hash(int value);
int lerp_int(float delta, int start, int end);
float lerp_float(float delta, float start, float end);
double lerp_double(double delta, double start, double end);
int lerp_positive(float delta, int start, int end);
double lerp_2(double deltax, double deltay, double x0y0, double x1y0, double x0y1, double x1y1);
double lerp_3(double delta_x, double delta_y, double delta_z, double x0y0z0, double x1y0z0, double x0y1z0, double x1y1z0, double x0y0z1, double x1y0z1, double x0y1z1, double x1y1z1);
float catmull_rom(float delta, float p0, float p1, float p2, float p3);
double perlin_fade(double value);
double perlin_fade_derivative(double value);
int sign(double value);
float lerp_angle_degrees_float(float delta, float start, float end);
double lerp_angle_degrees_double(double delta, double start, double end);
float lerp_angle_radians(float delta, float start, float end);
float wrap(float value, float max_deviation);
float square_float(float value);
double square_double(double value);
int square_int(int value);
long square_long(long value);
double clamped_map_double(double value, double old_start, double old_end, double new_start, double new_end);
float clamped_map_float(float value, float old_start, float old_end, float new_start, float new_end);
double map_double(double value, double old_start, double old_end, double new_start, double new_end);
float map_float(float value, float old_start, float old_end, float new_start, float new_end);
int round_up_to_multiple(int value, @NonZero int divisor);
int ceil_div(int a, @NonZero int b);
double squared_hypot(double a, double b);
double hypot_double(double a, double b);
float hypot_float(float a, float b);
double squared_magnitude(double a, double b, double c);
double magnitude_double(double a, double b, double c);
float magnitude_float(float a, float b, float c);
double magnitude_int(int a, double b, int c);
int round_down_to_multiple(double a, int b);
int multiply_fraction(int numerator, int denominator, int multiplier);
float wrap_degrees_90(float angle);
boolean is_power_of_2(long value);
long round_towards_long(long input, long multiple);
int round_towards_int(int input, int multiple);
long positive_ceil_div_long(long input, long divisor);
int positive_ceil_div_int(int input, int divisor);
}
